config/routes.rb
Rails.application.routes.draw do
  #GET /tweets(tweets#index), GET /tweets/new(tweets#new), Post /tweets(tweets#create)
  #only..生成されるルートを制限するために使われる。（index, new, create, show, edit, update, destroy
  #:tweetsがある場合、自動でルーディングヘルパーを生成する。tweets_path, new_tweet_path, edit_tweets_path, tweet_path(tweet): 特定のツイートを表示するページ(/tweets/:id)へのパス
  resources :tweets, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    # belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    # edit, update, destroyのアクションが実行されるまえに、set_tweetメソッドを実行する
    # before_action :authenticate_user!, except: [:index]
    before_action :set_tweet, only: [:edit, :update, :destroy]

    def index 
        # @tweets = Tweet.all
        @tweets = Tweet.order(created_at: :desc)
    end

    def new
        #新しいTweetオブジェクトをメモリ上に作成。まだDB上には保存されていない。
        @tweet = Tweet.new
    end
    def create
        @tweet = Tweet.new(tweet_params)
        # @tweet.user_id = User.first.id # here is where you're using User
      
        if @tweet.save
          redirect_to tweets_path
        else
          render :new
        end
      end

    def edit
    end

    def update
        if @tweet.update(tweet_params)
         redirect_to tweets_path
        else
            render :edit
        end
    end

    def destroy
        @tweet.destroy
        redirect_to tweet_path
    end

    #アクセス制御。そのクラス内部からのみアクセス可能なメソッド。
    #これを宣言した後に定義されたメソッドはは、そのクラス自体からのみ呼び出すことができる。
    #view等から直接、tweet_paramsを呼び出すことはできない。
    private

    #ストロングパラメータ
    def tweet_params
        #tweetキーの存在を必須とする。フォームから何か送信するとき、パラメータの中にtweetというキーがなければならない。
        #permit(:title, :content)...これらのパラメータのみを許可する。これ以外のパラメータは無視される。不正なデータ操作を防げる。
        params.require(:tweet).permit(:title, :content)
    end

   #DRY(Dont Repeat yourself)同じコードを繰り返し書くの防ぐため
   def set_tweet
    #:idで指定した投稿を取得して@tweetの内に格納している。
    @tweet = Tweet.find(params[:id])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleSns</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %> 
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/edit.html.erb
<h1>投稿編集</h1>

<%= form_with model: @tweet, local: true, html: {class: "form-container"} do
|form| %>
<div class="form-input">
  <div><%= form.label :title %> <%= form.text_field :title %></div>
</div>

<div class="form-input">
  <div><%= form.label :content %> <%= form.text_area :content %></div>
</div>

<div class="button-container">
  <%= form.submit '更新', class: "link-button" %>
</div>

<% end %>

app/views/tweets/index.html.erb
<h1>Ruby 掲示板</h1>

<div class="button-container">
  <%= link_to "新しい投稿", new_tweet_path, class: "link-button" %>
</div>

<ul>
  <% @tweets.each do |tweet| %>
  <li>
    <h2><%= tweet.title %></h2>

    <p><%= tweet.content %></p>
    <span>
      <small><%= tweet.created_at.strftime("%Y-%m-%d %H:%M") %></small>
    </span>
    <div class="edit-delete-wrapper">
      <%= link_to '編集', edit_tweet_path(tweet), class: "link-button" %> <%=
      button_to '削除', tweet_path(tweet), method: :delete, data: { confirm:
      '本当に削除しますか？' }, class: "link-delete-button" %>
    </div>
  </li>
  <% end %>
</ul>

app/views/tweets/new.html.erb
<h1>新しい投稿</h1>
<!-- formwith...フォームが送信されたときにデータをどこに送信するかを知っている必要がある。 -->
<!-- local: true...フォームデータの送信方式を指定。trueだとHTTPリクエストとして行われる。falseならAjax送信 -->
<%= form_with model: @tweet, local: true, html: {class: "form-container"} do
|form| %>
<div class="form-input">
  <%= form.label :title %> <%= form.text_field :title %>
</div>

<div class="form-input">
  <%= form.label :content %> <%= form.text_area :content %>
</div>
<div class="button-container">
  <%= form.submit "投稿", class: "link-button" %>
</div>
<% end %>